services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-smsservice

    ports:
      - "8082:8080"

    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    
  zookeeper:
    image: zookeeper
    container_name: zookeeper-smsservice
    restart: always

    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-smsservice
    depends_on:
      - zookeeper

    ports:
      - "9095:9094"

    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # listeners - listeners who listen connections inside the docker container
      #
      # in this example :9094 will be redirected to :9092
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094

      # advertised listeners - listeners who can also advertise their addresses
      # outside of the docker container
      #
      # kafka is accessible internally on port 9092, but it also translates 
      # as localhost:9095 outside of the container.
      # so out host can connect to kafka using localhost:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095

      # KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LOGS_DIR: /kafka/logs
      KAFKA_BROKER_ID: 500
      
      # configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
