services:
  sms-service:
    build: .
    environment:
      KAFKA_ADDRESS: "kafka:19092"
      BROKERS: "kafka:19092"
    depends_on:
      - kafka
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-smsservice

    ports:
      - "8082:8080"

    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    
  zookeeper:
    image: zookeeper
    container_name: zookeeper-smsservice
    restart: always

    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-smsservice
    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    volumes:
      - kafka-data:/var/lib/kafka/data

    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # in this example :9092 will be redirected to :19092
      KAFKA_LISTENERS: INTERNAL://kafka:19092,OUTSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LOGS_DIR: /kafka/logs
      KAFKA_BROKER_ID: 500
      
      # configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

volumes:
  kafka-data: