apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  namespace: sms-service
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
      - name: sms-service
        image: localhost:32000/sms-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: sms-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "600m"
            memory: "512Mi"
            
        livenessProbe:
          exec:
            command:
            - pgrep
            - sms-service
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pgrep
            - sms-service
          initialDelaySeconds: 5
          periodSeconds: 5