deployment:
  replicas: 1

  imageRegistryUrl: localhost:32000
  imageName: sms-service
  imageVersion: latest

  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "600m"
    memory: "512Mi"

secret:
  KAFKA_ADDRESS: "kafka-service.shared-services.svc.cluster.local:9092"

service:
  port: 15691
