apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  namespace: sms-service
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
      - name: sms-service
        image: {{ .Values.deployment.imageRegistryUrl }}/{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: sms-secrets
        resources:
          requests:
            cpu: {{ .Values.deployment.requests.cpu }}
            memory: {{ .Values.deployment.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.limits.cpu }}
            memory: {{ .Values.deployment.limits.memory }}